import type { ShopProduct, ShopReview } from './types';

let reviewCounter = 0;

function r(
  author: string,
  rating: ShopReview['rating'],
  text: string,
  daysAgo: number,
  verified = true
): ShopReview {
  reviewCounter += 1;
  return { id: `rev-${reviewCounter}`, author, rating, text, daysAgo, verified };
}

export const SHOP_PRODUCTS: ShopProduct[] = [
  // ---------------------------------------------------------------- SAREES
  {
    id: 'saree-banarasi-01',
    name: 'Kanjeevaram-Style Banarasi Silk Saree',
    brand: 'Vastraa Weaves',
    category: 'Sarees',
    emoji: '🥻',
    swatch: 'linear-gradient(135deg,#7a1230,#c9932f)',
    price: 4999,
    mrp: 7999,
    avgRating: 4.3,
    ratingCount: 812,
    attributes: {
      fabric: 'Pure silk blend with zari woven border and pallu',
      fit: 'One-size drape — needs a separately stitched blouse and petticoat',
      occasion: 'Weddings, festive pujas, formal receptions',
      reusability: 'Best for 1-2 major events a year, not everyday wear',
      deliveryEstimate: '5-7 days, arrives in a branded saree box',
      returnPolicy: '7-day return, tags must be attached',
    },
    reviews: [
      r('Priya', 5, 'Wore this to my brother’s wedding, the silk feels genuinely premium and the zari border catches light beautifully.', 12),
      r('Sneha', 4, 'Gorgeous saree but very heavy to drape alone — had to get help from a parlour before the function.', 20),
      r('Meera', 5, 'Worth every rupee for a wedding. Got so many compliments, feels like a family heirloom already.', 34),
      r('Rohit', 3, 'Bought for my wife, color was slightly darker than the photo but still looks rich in person.', 40),
      r('Ananya', 4, 'Good quality zari work. Delivery took 6 days which was fine since I ordered a month ahead.', 8, false),
      r('Divya', 2, 'Nice fabric but honestly feels like a one-time-wear item for the price — won’t reuse this often.', 55),
      r('Riya', 5, 'The pallu design is stunning, exactly like the store photos. Packaging was premium too.', 15),
      r('Kabir', 3, 'Got this for my mother. She loved the silk but said draping needs practice, not beginner friendly.', 62),
      r('Isha', 5, 'Perfect for my cousin’s wedding reception. Traditional look, doesn’t feel cheap at all.', 5),
      r('Tanvi', 4, 'Blouse piece included is unstitched so factor in extra tailoring time before your event.', 28),
      r('Neha', 5, 'Five stars — the silk sheen is real, not the fake shiny synthetic look some sarees have.', 47),
      r('Arjun', 2, 'Expensive for something I’ll wear maybe once a year. Quality is good but reusability is low.', 70),
      r('Simran', 4, 'Delivery was on time, saree box made it feel like a proper gift. Draping does take effort.', 18, false),
      r('Yash', 5, 'Bought for wedding season, exactly the traditional look I wanted. Fabric feels durable.', 3),
      r('Pooja', 3, 'Beautiful but pricey. If you only need it for one wedding, consider renting instead.', 44),
    ],
  },
  {
    id: 'saree-chiffon-02',
    name: 'Printed Chiffon Saree',
    brand: 'AURELIA',
    category: 'Sarees',
    emoji: '🥻',
    swatch: 'linear-gradient(135deg,#1f6b6b,#f2a6c1)',
    price: 1499,
    mrp: 2299,
    avgRating: 4.0,
    ratingCount: 1120,
    attributes: {
      fabric: 'Lightweight printed chiffon with a simple satin border',
      fit: 'One-size drape, easy to manage even for beginners',
      occasion: 'Office wear, casual family functions, day events — not heavy wedding wear',
      reusability: 'Very high — light enough for weekly office wear',
      deliveryEstimate: '3-4 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Priya', 5, 'Wear this to office at least twice a month, super light and doesn’t crease easily.', 6),
      r('Karan', 4, 'Good everyday saree, easy to drape myself without help unlike heavier silk ones.', 19),
      r('Meera', 3, 'Print faded slightly after a couple of washes, still decent for the price.', 33),
      r('Isha', 5, 'Most reused saree in my closet — office, pujas, casual visits, all covered.', 11),
      r('Rohit', 4, 'Bought for my mother, she says it’s very comfortable for all-day wear.', 45),
      r('Sanjay', 2, 'Fabric is thinner than expected, needed a proper petticoat underneath for opacity.', 58),
      r('Ananya', 5, 'Great value chiffon saree, drapes beautifully and is genuinely wearable every week.', 3),
      r('Divya', 4, 'True one-size drape, easiest saree I’ve worn to manage on my own.', 27),
      r('Riya', 3, 'Nice for office but too plain for anything festive, wouldn’t wear to a wedding.', 41),
      r('Tanvi', 5, 'Delivery was quick, saree feels lightweight and perfect for daily wear.', 9),
      r('Neha', 4, 'Good basic saree for the price, reused it constantly for work.', 52),
      r('Vikram', 5, 'Bought several for my wife, she wears these on rotation for office.', 15),
      r('Kabir', 2, 'Border started fraying after a few wears, quality could be better.', 64),
      r('Simran', 4, 'Comfortable and breathable, good for long office days.', 22, false),
      r('Aditya', 5, 'Best reusable saree I own, wear it almost weekly without any issues.', 37),
    ],
  },
  {
    id: 'saree-kanjeevaram-03',
    name: 'Pure Kanjeevaram Silk Saree',
    brand: 'Pothys',
    category: 'Sarees',
    emoji: '🥻',
    swatch: 'linear-gradient(135deg,#0b3d24,#c9932f)',
    price: 6999,
    mrp: 9999,
    avgRating: 4.6,
    ratingCount: 402,
    attributes: {
      fabric: '100% pure Kanjeevaram silk with temple border zari work',
      fit: 'One-size drape, heavier fabric needs an experienced draper',
      occasion: 'Weddings, temple functions, formal receptions — premium traditional wear',
      reusability: 'Lowest reusability of all sarees — reserved for one major event a year',
      deliveryEstimate: '6-8 days, insured shipping',
      returnPolicy: '7-day return, tags attached',
    },
    reviews: [
      r('Meera', 5, 'This is heirloom quality. Wore it for my wedding reception, absolutely worth the price.', 40),
      r('Priya', 5, 'The zari work is exceptional, easily the finest saree I own.', 14),
      r('Rohit', 4, 'Bought for my mother-in-law, she was thrilled. Heavy fabric so drape carefully.', 25),
      r('Divya', 3, 'Beautiful but extremely expensive for something worn once a year at most.', 58),
      r('Ananya', 5, 'Genuinely pure silk, you can feel the difference from synthetic blends immediately.', 8),
      r('Karan', 4, 'Delivery took a full week but the insured packaging felt reassuring for this price.', 33),
      r('Isha', 5, 'Wore this to a temple wedding function, felt every bit as premium as it looks.', 3),
      r('Sanjay', 2, 'Gorgeous saree but honestly too formal and heavy for anything but a major wedding.', 66),
      r('Riya', 5, 'The temple border design is stunning in person, better than the photos even.', 19),
      r('Tanvi', 4, 'Heaviest saree I own, needs an experienced hand to drape well for the occasion.', 47),
      r('Neha', 5, 'This is a once-in-a-decade purchase kind of saree — pure luxury silk.', 6),
      r('Kabir', 3, 'Quality is undeniable but reusability is basically zero given how formal it is.', 52),
      r('Simran', 5, 'Bought for my own wedding, no regrets — the silk sheen is incredible.', 11, false),
      r('Vikram', 4, 'Pricey but the craftsmanship justifies it if you need something for a big wedding.', 38),
      r('Pooja', 5, 'Premium in every sense, exactly what I wanted for my sister’s wedding.', 21),
    ],
  },
  {
    id: 'saree-georgette-04',
    name: 'Embellished Georgette Party Saree',
    brand: 'Soch',
    category: 'Sarees',
    emoji: '🥻',
    swatch: 'linear-gradient(135deg,#4a2b6b,#c0c0c0)',
    price: 2799,
    mrp: 3999,
    avgRating: 4.2,
    ratingCount: 764,
    attributes: {
      fabric: 'Georgette with stone and sequin embellishment',
      fit: 'One-size drape, lightweight and easy to pleat',
      occasion: 'Sangeet, cocktail parties, festive get-togethers — semi-formal',
      reusability: 'Medium-high — reworn across 2-3 party-style events a year',
      deliveryEstimate: '4-5 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Riya', 5, 'Wore this to a sangeet, the sequin work catches so much light on the dance floor.', 9),
      r('Ananya', 4, 'Good semi-formal option, reworn it for two different cocktail parties already.', 22),
      r('Meera', 3, 'A few sequins came loose after the first wear, minor but noticeable.', 35),
      r('Karan', 5, 'Lightweight georgette makes it so much easier to pleat than stiffer silk sarees.', 5),
      r('Divya', 4, 'Great for festive parties, not too heavy, easy to move around and dance in.', 44),
      r('Sanjay', 2, 'Embellishment started shedding a bit near the border after dry cleaning.', 58),
      r('Isha', 5, 'Perfect for my cousin’s sangeet, got so many compliments on the sparkle.', 3),
      r('Tanvi', 4, 'Reusable for multiple festive events, comfortable to wear all evening.', 30),
      r('Neha', 3, 'Nice saree but color was slightly duller in person compared to photos.', 49),
      r('Rohit', 5, 'Bought for my wife for a cocktail event, she loved how lightweight it felt.', 12),
      r('Kabir', 4, 'Good balance of festive sparkle without being as heavy as bridal silk.', 26, false),
      r('Simran', 5, 'Wore it twice already this wedding season for different sangeets.', 17),
      r('Vikram', 3, 'Decent quality, embellishment is nice but not as dense as expected.', 53),
      r('Priya', 4, 'Easy to drape and pleat, great for a fun festive evening event.', 39),
      r('Aditya', 5, 'This has become my go-to for every sangeet invite this season.', 7),
    ],
  },
  {
    id: 'saree-cotton-05',
    name: 'Handloom Cotton Saree',
    brand: 'Fabindia',
    category: 'Sarees',
    emoji: '🥻',
    swatch: 'linear-gradient(135deg,#8a5a12,#f5f0e6)',
    price: 1199,
    mrp: 1799,
    avgRating: 4.1,
    ratingCount: 1543,
    attributes: {
      fabric: 'Pure handloom cotton, breathable everyday weave',
      fit: 'One-size drape, lightest of all sarees, easiest to manage',
      occasion: 'Daily office wear, pujas, casual family gatherings',
      reusability: 'Extremely high — genuinely everyday wearable',
      deliveryEstimate: '3-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Meera', 5, 'Wear this at least once a week, most comfortable saree I own for daily use.', 4),
      r('Tanvi', 4, 'Great handloom quality for the price, holds up well after many washes.', 18),
      r('Priya', 5, 'Perfect for pujas and casual family visits, easy to drape and breathable.', 29),
      r('Rohit', 3, 'Good cotton but slightly stiff initially, softened after a couple of washes.', 41),
      r('Ananya', 5, 'Best budget saree I’ve bought, reuse it constantly for office.', 6),
      r('Karan', 4, 'True handloom texture, lightweight and easy to manage even for beginners.', 35, false),
      r('Divya', 2, 'Color started fading a bit faster than expected after several washes.', 60),
      r('Isha', 5, 'Extremely reusable, this is my everyday go-to saree now.', 12),
      r('Sanjay', 4, 'Good quality cotton for the price point, comfortable all day.', 47),
      r('Riya', 5, 'Bought several for my mother, she wears these for daily pujas.', 3),
      r('Neha', 3, 'Decent saree but a bit plain looking, fine for daily wear only.', 53),
      r('Kabir', 4, 'Breathable and light, perfect for humid weather and long days.', 25),
      r('Simran', 5, 'Best value handloom saree, wear it almost every week without issue.', 15),
      r('Vikram', 4, 'Good for office and casual events, easy to maintain and reuse.', 38),
      r('Pooja', 5, 'Extremely comfortable, this is genuinely an everyday-wearable saree.', 9),
    ],
  },

  // ---------------------------------------------------------- ETHNIC WEAR
  {
    id: 'anarkali-suit-01',
    name: 'Embroidered Floor-Length Anarkali Suit Set',
    brand: 'Libas',
    category: 'Ethnic Wear',
    emoji: '👗',
    swatch: 'linear-gradient(135deg,#0f5c5c,#c9932f)',
    price: 3499,
    mrp: 5499,
    avgRating: 4.1,
    ratingCount: 1284,
    attributes: {
      fabric: 'Georgette with thread embroidery, comes with matching dupatta',
      fit: 'Runs large by about one size, flowy floor-length silhouette',
      occasion: 'Weddings, sangeet, festive parties — semi-formal',
      reusability: 'Restyle with different jewelry/footwear for 3-4 events a year',
      deliveryEstimate: '4-6 days standard delivery',
      returnPolicy: '10-day return window',
    },
    reviews: [
      r('Ananya', 5, 'Wore this to my cousin’s sangeet and got so many compliments. Traditional but not over the top.', 10),
      r('Vikram', 3, 'Ordered my usual size, came out loose. Would size down by one for a fitted look.', 25),
      r('Divya', 4, 'Embroidery is neat, though I noticed a couple of loose threads near the sleeve on arrival.', 33),
      r('Karan', 5, 'Great value — traditional enough for a wedding but light enough to reuse for other festive events.', 6),
      r('Riya', 4, 'Runs large, ordered a size down based on other reviews and it fit perfectly.', 41),
      r('Sanjay', 2, 'The color was more muted than shown in photos, still decent quality fabric though.', 58),
      r('Neha', 5, 'Perfect for my sister’s wedding functions, wore it twice with different dupattas and jewelry.', 14),
      r('Isha', 3, 'Good fit true to size for me, but the dupatta fabric feels thinner than the suit itself.', 22, false),
      r('Aditya', 4, 'Reasonably priced for the embroidery detail. Delivery was quick, arrived in 4 days.', 3),
      r('Simran', 5, 'This is genuinely reusable — wore it for sangeet and again for a friend’s reception.', 49),
      r('Pooja', 3, 'Nice suit but sizing chart is inaccurate, definitely order one size smaller than usual.', 37),
      r('Tanvi', 4, 'Fabric quality is good for the price. Semi-formal so doesn’t feel too heavy to wear.', 19),
      r('Rahul', 5, 'Bought for my wife for a wedding, she loved how comfortable it was compared to a saree.', 8),
      r('Meera', 2, 'Embroidery started coming loose after one wash, be careful with dry-clean only instructions.', 66),
      r('Kabir', 4, 'Solid pick if you want something traditional but reusable across multiple wedding events.', 27),
    ],
  },
  {
    id: 'kurta-set-men-01',
    name: 'Silk Blend Kurta Pajama with Nehru Jacket',
    brand: 'Manyavar',
    category: 'Ethnic Wear',
    emoji: '👘',
    swatch: 'linear-gradient(135deg,#3a2b1a,#c9932f)',
    price: 2999,
    mrp: 4499,
    avgRating: 4.5,
    ratingCount: 956,
    attributes: {
      fabric: 'Silk blend kurta with contrast Nehru jacket',
      fit: 'True to size, tailored fit through the chest and shoulders',
      occasion: 'Weddings, festive functions, reusable for pujas too',
      reusability: 'High — jacket and kurta can be worn separately for other events',
      deliveryEstimate: '4-5 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Rohit', 5, 'Wore this as a guest at a wedding, fit was true to size and looked sharp with the jacket.', 9),
      r('Arjun', 5, 'Can wear the kurta alone for a puja and the jacket separately over a shirt — very reusable.', 21),
      r('Sanjay', 4, 'Good quality fabric, fits true to size. Only wish the sleeves were slightly longer.', 15),
      r('Yash', 5, 'Perfect for my cousin’s wedding. Traditional look but the jacket makes it modern enough to reuse.', 4),
      r('Karan', 3, 'Nice set, but the jacket color faded slightly after first dry clean.', 45),
      r('Vikram', 4, 'True to size for me, ordered based on the size chart with no issues.', 30),
      r('Aditya', 5, 'Best value ethnic wear I’ve bought — reused this for three different family functions already.', 60),
      r('Kabir', 4, 'Comfortable fabric, doesn’t feel stiff like some silk-blend kurtas. Delivery was prompt.', 11),
      r('Rahul', 5, 'Exactly what I needed for a wedding — traditional, comfortable, and I’ll definitely wear it again.', 2),
      r('Sanjay', 2, 'Fit was slightly tight around the shoulders even though I ordered my usual size.', 52),
      r('Ananya', 5, 'Bought for my husband, he loved how versatile it is — jacket works with jeans too.', 38),
      r('Divya', 4, 'Great quality for the price. Only 4 stars because packaging had a slight crease.', 24, false),
      r('Neha', 5, 'This is the definition of traditional but reusable. Highly recommend for wedding season.', 17),
      r('Isha', 3, 'Decent kurta set, fit runs true to size but fabric is thinner than expected for the price.', 48),
      r('Riya', 5, 'Bought for my brother’s wedding — he’s worn it to two more functions since. Great investment.', 6),
    ],
  },
  {
    id: 'palazzo-set-women-01',
    name: 'Printed Palazzo Co-ord Set',
    brand: 'Global Desi',
    category: 'Ethnic Wear',
    emoji: '👚',
    swatch: 'linear-gradient(135deg,#8a5a12,#e8c96b)',
    price: 1999,
    mrp: 2999,
    avgRating: 3.9,
    ratingCount: 1502,
    attributes: {
      fabric: 'Lightweight rayon, printed kurta with palazzo pants',
      fit: 'True to size, relaxed comfortable fit',
      occasion: 'Casual-ethnic fusion — daytime functions, mehendi, not main ceremony wear',
      reusability: 'Very high — comfortable enough for everyday and multiple casual events',
      deliveryEstimate: '3-4 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Meera', 4, 'Super comfortable for a daytime mehendi function, though it’s not formal enough for the main wedding.', 7),
      r('Tanvi', 5, 'Best reusability of anything I own — wear it to work, to casual get-togethers, everywhere.', 13),
      r('Pooja', 3, 'Nice and breezy fabric but feels too casual if you’re looking for wedding-formal wear.', 26),
      r('Simran', 4, 'True to size and genuinely comfortable all day. Great for pre-wedding functions.', 19),
      r('Rahul', 5, 'Bought for my wife, she wears it constantly — most reused item in her closet now.', 35),
      r('Karan', 2, 'Fabric feels a bit thin and see-through in bright light, needed a slip underneath.', 42),
      r('Neha', 4, 'Good for budget-conscious buyers who want something ethnic but affordable and versatile.', 5),
      r('Vikram', 5, 'Perfect for a sangeet-adjacent lunch event, comfortable and still looks put-together.', 50),
      r('Riya', 3, 'Print quality is decent but not as vibrant as the website photos suggested.', 31),
      r('Aditya', 4, 'Bought this for my sister for a mehendi ceremony, she loved the comfort and reused it after.', 3),
      r('Sanjay', 5, 'Fits true to size, lightweight for summer weddings. Highly reusable across casual occasions.', 61),
      r('Isha', 2, 'Feels more like loungewear than event wear, wouldn’t recommend for the main wedding day.', 55),
      r('Kabir', 4, 'Good value for money, delivery was quick. Comfortable fit, not too tight or loose.', 17),
      r('Divya', 5, 'This has become my go-to for every casual festive event since I bought it.', 40, false),
      r('Ananya', 3, 'Nice for daytime functions but definitely not traditional enough for the actual ceremony.', 47),
    ],
  },
  {
    id: 'sharara-set-04',
    name: 'Embroidered Sharara Suit Set',
    brand: 'Aachho',
    category: 'Ethnic Wear',
    emoji: '👗',
    swatch: 'linear-gradient(135deg,#8a1a4a,#e8c96b)',
    price: 3999,
    mrp: 5999,
    avgRating: 4.0,
    ratingCount: 388,
    attributes: {
      fabric: 'Silk blend kurta with heavily embroidered sharara pants and dupatta',
      fit: 'Runs true to size but the flared sharara needs the right footwear and height',
      occasion: 'Weddings, sangeet — statement wear, less everyday reusable',
      reusability: 'Low — heavy embellishment limits it to one or two big events a year',
      deliveryEstimate: '5-6 days',
      returnPolicy: '7-day return',
    },
    reviews: [
      r('Riya', 5, 'Wore this to a sangeet, the sharara flare looks amazing on the dance floor.', 8),
      r('Divya', 4, 'True to size, though I needed heels to keep the sharara from dragging.', 21),
      r('Meera', 3, 'Gorgeous embroidery but definitely a one-or-two-wear item given how statement it is.', 34),
      r('Karan', 5, 'Bought for my wife for a wedding, she felt like a showstopper in this.', 5),
      r('Sanjay', 2, 'Beautiful but very heavy embroidery makes it hard to sit comfortably for long.', 47),
      r('Ananya', 4, 'True to size, the dupatta drape adds a nice traditional touch.', 29),
      r('Isha', 5, 'This is peak wedding wear — traditional, statement-making, unforgettable.', 3),
      r('Vikram', 3, 'Nice set but not something I’d call reusable, very occasion-specific.', 53),
      r('Neha', 4, 'Good quality embroidery, held up well through a full evening of dancing.', 16),
      r('Tanvi', 5, 'Perfect for my cousin’s wedding sangeet, exactly the traditional statement look I wanted.', 12, false),
      r('Kabir', 2, 'Beautiful but the flare makes movement tricky, tripped a couple of times.', 60),
      r('Simran', 4, 'True to size, heavy but worth it for a big wedding function.', 38),
      r('Rohit', 5, 'Bought for my sister’s sangeet, she loved the dramatic silhouette.', 7),
      r('Priya', 3, 'Gorgeous but definitely single-occasion wear given the embellishment level.', 44),
      r('Aditya', 4, 'Good craftsmanship, reworked the dupatta styling for a second event successfully.', 25),
    ],
  },
  {
    id: 'dhoti-kurta-men-05',
    name: 'Cotton Silk Dhoti Kurta Set',
    brand: 'Fabindia',
    category: 'Ethnic Wear',
    emoji: '👘',
    swatch: 'linear-gradient(135deg,#6b3a1a,#f5e6c8)',
    price: 2499,
    mrp: 3499,
    avgRating: 4.3,
    ratingCount: 512,
    attributes: {
      fabric: 'Cotton silk kurta with pre-stitched dhoti pants',
      fit: 'True to size, pre-stitched dhoti removes the draping hassle',
      occasion: 'Festive pujas, weddings, traditional seasonal functions',
      reusability: 'Medium-high — reworn across the festive season, less for weddings only',
      deliveryEstimate: '4-5 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Arjun', 5, 'Pre-stitched dhoti is a lifesaver, no draping skills needed and still looks authentic.', 6),
      r('Rahul', 4, 'True to size, wore this for a wedding and again for a puja later.', 20),
      r('Sanjay', 5, 'Best decision for someone who can’t drape a traditional dhoti — looks great regardless.', 33),
      r('Yash', 3, 'Good quality but the kurta fabric could be a bit softer for all-day wear.', 45),
      r('Vikram', 5, 'Reused this across two festive functions already, comfortable and easy to wear.', 9),
      r('Karan', 4, 'True to size, cotton silk blend feels breathable even in warm weather.', 27),
      r('Aditya', 2, 'Dhoti pants felt a bit loose at the ankle even at the right size.', 58),
      r('Kabir', 5, 'Perfect for traditional functions, reusable across the whole festive season.', 14),
      r('Rohit', 4, 'Comfortable fit, good for pujas and casual traditional events alike.', 41),
      r('Sanjay', 5, 'Bought for my father, he loves how easy the pre-stitched dhoti is.', 4),
      r('Ananya', 3, 'Nice set but fabric wrinkles more than expected through the day.', 50),
      r('Divya', 4, 'Good value traditional wear, true to size and comfortable.', 23, false),
      r('Neha', 5, 'This has become our family’s go-to for every festive occasion now.', 17),
      r('Isha', 4, 'True to size, reusable for multiple traditional functions across the year.', 36),
      r('Riya', 5, 'Great alternative to a full sherwani — lighter and just as festive.', 11),
    ],
  },

  // -------------------------------------------------------- WESTERN WEAR
  {
    id: 'floral-wrap-dress-01',
    name: 'Floral Print Wrap Maxi Dress',
    brand: 'AND',
    category: 'Western Wear',
    emoji: '👗',
    swatch: 'linear-gradient(135deg,#c65b8a,#f6d9a0)',
    price: 2199,
    mrp: 3499,
    avgRating: 4.0,
    ratingCount: 943,
    attributes: {
      fabric: 'Crepe fabric, wrap-style with adjustable waist tie',
      fit: 'True to size, adjustable wrap allows some flexibility',
      occasion: 'Daytime parties, brunches, casual outings — not ethnic occasions',
      reusability: 'High for casual wear, not suited to traditional functions',
      deliveryEstimate: '3-5 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Riya', 5, 'Beautiful print, fits true to size and the wrap tie means it adjusts if your weight fluctuates.', 8),
      r('Sneha', 4, 'Great for brunches and daytime events, wouldn’t work for a traditional function though.', 22),
      r('Priya', 3, 'Fabric is a bit thin, can see through in direct sunlight, needed a slip.', 36),
      r('Meera', 5, 'Perfect for a friend’s pre-wedding brunch, comfortable and easy to move around in.', 11),
      r('Karan', 4, 'True to size, delivery was fast. Good casual option but very western in style.', 44),
      r('Ananya', 2, 'Color faded slightly after one wash despite following care instructions.', 58),
      r('Vikram', 5, 'Wife wore this to a cousin’s mehendi daytime event, looked elegant and stayed comfortable.', 15),
      r('Isha', 4, 'Nice quality for the price, wrap style is flattering and true to size.', 29),
      r('Rohit', 3, 'Decent dress but definitely a western silhouette, not for anything traditional.', 51),
      r('Tanvi', 5, 'Reused this for three different casual outings already, great versatile buy.', 6),
      r('Sanjay', 4, 'Good fit, fabric quality better than expected at this price point.', 39),
      r('Divya', 3, 'Nice for a daytime look but not appropriate for evening or ceremony events.', 63),
      r('Kabir', 5, 'Bought for my sister, she loves how easy it is to dress up or down.', 4),
      r('Neha', 2, 'Wrap tie came slightly loose after a few wears, had to restitch it.', 47),
      r('Yash', 4, 'True to size, comfortable for all-day wear at outdoor daytime events.', 20, false),
    ],
  },
  {
    id: 'denim-jacket-women-01',
    name: 'Classic Denim Jacket',
    brand: 'Roadster',
    category: 'Western Wear',
    emoji: '🧥',
    swatch: 'linear-gradient(135deg,#2b4a6b,#6a9bc4)',
    price: 1799,
    mrp: 2699,
    avgRating: 4.0,
    ratingCount: 1345,
    attributes: {
      fabric: 'Cotton denim, medium wash',
      fit: 'True to size, slightly boxy oversized silhouette',
      occasion: 'Casual, layering piece for everyday and travel',
      reusability: 'Extremely high — year-round layering staple',
      deliveryEstimate: '3-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Simran', 5, 'My most reused jacket, works over almost anything casual.', 9),
      r('Rahul', 4, 'True to size, slightly boxy fit which I actually like for layering.', 20),
      r('Neha', 5, 'Great quality denim for the price, holds up well after multiple washes.', 33),
      r('Karan', 3, 'Fit is a bit oversized, would size down if you want a fitted look.', 46),
      r('Ananya', 4, 'Perfect travel layering piece, reused this constantly on my last trip.', 6),
      r('Divya', 5, 'Classic denim jacket that goes with everything, extremely versatile.', 28),
      r('Vikram', 2, 'Color faded slightly faster than expected after a few washes.', 55),
      r('Priya', 4, 'True to size, good quality denim, comfortable for daily wear.', 15),
      r('Sanjay', 5, 'Bought this two years ago and still wear it weekly, great investment.', 61),
      r('Isha', 3, 'Nice jacket but the boxy fit isn’t for everyone, check measurements first.', 40),
      r('Kabir', 4, 'Solid quality denim, reusable across seasons as a layering piece.', 24),
      r('Riya', 5, 'Extremely comfortable and versatile, my go-to casual jacket now.', 3, false),
      r('Meera', 4, 'True to size, good stitching quality, no complaints after months of use.', 37),
      r('Aditya', 3, 'Decent jacket, fit runs slightly large so consider sizing down.', 49),
      r('Tanvi', 5, 'Best casual jacket purchase this year, wear it almost every week.', 11),
    ],
  },
  {
    id: 'jumpsuit-03',
    name: 'Solid Culotte Jumpsuit',
    brand: 'Vero Moda',
    category: 'Western Wear',
    emoji: '👖',
    swatch: 'linear-gradient(135deg,#3a4a2b,#8a9a6b)',
    price: 1999,
    mrp: 2999,
    avgRating: 3.9,
    ratingCount: 621,
    attributes: {
      fabric: 'Crepe fabric, wide-leg culotte silhouette',
      fit: 'True to size, adjustable waist tie for flexibility',
      occasion: 'Casual outings, work-from-office days, brunches',
      reusability: 'High — one-piece convenience for regular wear',
      deliveryEstimate: '3-4 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Tanvi', 5, 'One-piece convenience is unmatched, throw it on and go, wear it weekly.', 7),
      r('Meera', 4, 'True to size, waist tie makes it flexible for bloating days too.', 19),
      r('Karan', 3, 'Nice for brunches but the wide leg makes it tricky in windy weather.', 31),
      r('Riya', 5, 'Extremely comfortable for work-from-office days, reused it constantly.', 4),
      r('Sanjay', 2, 'Fabric wrinkles more than expected by the end of the day.', 48),
      r('Divya', 4, 'Good fit, true to size, versatile for casual outings and errands.', 26),
      r('Isha', 5, 'Bought two more after loving the first, super comfortable jumpsuit.', 12),
      r('Vikram', 3, 'Decent quality but color options were limited when I ordered.', 55),
      r('Neha', 4, 'True to size, easy to dress up with accessories for brunch.', 38, false),
      r('Kabir', 5, 'Most comfortable thing I own for casual Fridays at work.', 3),
      r('Priya', 2, 'Waist tie came undone a few times during the day, minor annoyance.', 60),
      r('Ananya', 4, 'Good one-piece option, reusable for both errands and casual meetups.', 22),
      r('Simran', 5, 'Extremely versatile, wear it at least once a week now.', 15),
      r('Rohit', 3, 'Bought for my wife, she says it runs true to size and is comfy.', 44),
      r('Aditya', 4, 'Nice culotte silhouette, good for both casual and semi-casual settings.', 33),
    ],
  },
  {
    id: 'skirt-top-set-04',
    name: 'Co-ord Skirt & Crop Top Set',
    brand: 'ONLY',
    category: 'Western Wear',
    emoji: '👚',
    swatch: 'linear-gradient(135deg,#e06a4a,#f6c9a0)',
    price: 1699,
    mrp: 2499,
    avgRating: 3.8,
    ratingCount: 445,
    attributes: {
      fabric: 'Cotton-lycra blend, stretchable fit',
      fit: 'Runs slightly small on top, true to size on skirt',
      occasion: 'Casual day parties, college events, brunches',
      reusability: 'High — mix-and-match separately with other basics',
      deliveryEstimate: '3-5 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Riya', 4, 'Top runs a bit small, sized up for the top and it fit perfectly.', 10),
      r('Isha', 5, 'Love that I can wear the skirt and top separately with other outfits.', 23),
      r('Tanvi', 3, 'Cute set but the crop top is tighter than expected at true size.', 36),
      r('Meera', 4, 'Good stretchable fabric, comfortable for a day party or brunch.', 5),
      r('Sanjay', 2, 'Fabric quality feels a bit cheap for the price point.', 49),
      r('Ananya', 5, 'Mix-and-match value is great, reused pieces separately many times.', 17),
      r('Karan', 3, 'True to size on the skirt, top definitely runs small, size up.', 41),
      r('Divya', 4, 'Good for college events, comfortable stretch fabric all day.', 28, false),
      r('Vikram', 5, 'Bought for my sister, she wears the pieces separately constantly now.', 8),
      r('Neha', 2, 'Color was slightly different from the site photos, still wearable.', 54),
      r('Kabir', 4, 'Nice casual set, true to size on bottom, size up on top.', 32),
      r('Priya', 3, 'Decent quality for the price, good for casual day outings.', 46),
      r('Simran', 5, 'Great versatility, wear the skirt with different tops regularly.', 13),
      r('Rohit', 4, 'Bought for my wife, she likes mixing these pieces into other outfits.', 39),
      r('Aditya', 3, 'Good for brunches but crop top runs small, order a size up.', 21),
    ],
  },
  {
    id: 'bodycon-dress-05',
    name: 'Ribbed Bodycon Midi Dress',
    brand: 'Forever 21',
    category: 'Western Wear',
    emoji: '👗',
    swatch: 'linear-gradient(135deg,#1a1a1a,#c0304a)',
    price: 1899,
    mrp: 2799,
    avgRating: 4.0,
    ratingCount: 890,
    attributes: {
      fabric: 'Ribbed stretch knit fabric',
      fit: 'True to size, form-fitting silhouette',
      occasion: 'Date nights, birthday parties, evening casual events',
      reusability: 'Medium — best for evening occasions, not everyday wear',
      deliveryEstimate: '3-4 days',
      returnPolicy: '10-day return',
    },
    reviews: [
      r('Neha', 5, 'Perfect for a birthday party, true to size and the ribbed fabric is flattering.', 6),
      r('Riya', 4, 'Good stretch fit, comfortable for a night out, true to size.', 18),
      r('Divya', 3, 'Nice dress but definitely evening-only, wouldn’t wear it casually during the day.', 32),
      r('Isha', 5, 'Wore this on a date night, fit was perfect and felt confident all evening.', 4),
      r('Karan', 2, 'Fabric pilled slightly after the first wash, disappointing for the price.', 47),
      r('Meera', 4, 'True to size, form-fitting but comfortable enough for a few hours out.', 25),
      r('Sanjay', 5, 'Bought for my wife’s birthday dinner, she loved the fit and look.', 3),
      r('Vikram', 3, 'Good for evening events but definitely not an everyday reusable piece.', 51),
      r('Tanvi', 4, 'Nice ribbed texture, true to size, flattering silhouette for parties.', 14, false),
      r('Ananya', 5, 'This is my go-to for birthday parties and date nights now.', 9),
      r('Kabir', 2, 'Runs a touch tight around the hips even at the correct size.', 58),
      r('Priya', 4, 'Good quality knit, comfortable enough for a few hours of dancing.', 36),
      r('Simran', 5, 'Perfect evening dress, true to size and great fabric quality.', 12),
      r('Rohit', 3, 'Bought for my sister, she says it’s great for parties but nothing else.', 43),
      r('Aditya', 4, 'True to size, good for evening casual events, reused it twice already.', 27),
    ],
  },

  // --------------------------------------------------------- FORMAL WEAR
  {
    id: 'blazer-men-01',
    name: 'Slim Fit Formal Blazer',
    brand: 'Van Heusen',
    category: 'Formal Wear',
    emoji: '🧥',
    swatch: 'linear-gradient(135deg,#1a2740,#4a6fa5)',
    price: 3299,
    mrp: 4999,
    avgRating: 4.2,
    ratingCount: 671,
    attributes: {
      fabric: 'Polyester-viscose blend, structured shoulders',
      fit: 'Slim fit, runs slightly tight — order one size up if broad-shouldered',
      occasion: 'Office formals, interviews, semi-formal evening events',
      reusability: 'Very high — works for office and formal events year-round',
      deliveryEstimate: '3-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Arjun', 5, 'Perfect for interviews and office, structured shoulders make it look sharp without feeling stiff.', 10),
      r('Rahul', 3, 'Slim fit runs tight, had to exchange for a size up since I have broader shoulders.', 24),
      r('Vikram', 5, 'Reused this for office, a wedding reception, and a formal dinner — extremely versatile.', 33),
      r('Karan', 4, 'Good quality fabric for the price, fits well if you go true to size.', 18),
      r('Sanjay', 4, 'Sharp look, wore it for a cousin’s reception over a kurta-style shirt, worked surprisingly well.', 41),
      r('Aditya', 2, 'Fit was too tight across the chest, needed to size up by one.', 55),
      r('Yash', 5, 'One of my most reused pieces — office five days a week, plus every formal event.', 7),
      r('Kabir', 4, 'Good structure, doesn’t wrinkle easily. True to size if you’re average build.', 29),
      r('Rohit', 5, 'Great value blazer, reusable across so many occasions unlike single-use ethnic wear.', 3),
      r('Divya', 3, 'Fabric feels a little synthetic up close but looks great from a distance.', 47),
      r('Meera', 4, 'Bought for my husband, he wears it constantly for work and semi-formal dinners.', 60),
      r('Simran', 5, 'Delivery was quick, fit was exactly as expected. Highly reusable investment piece.', 14),
      r('Neha', 2, 'Runs small in the shoulders, would recommend sizing up if in doubt.', 52),
      r('Priya', 4, 'Good all-rounder blazer, works for office and dressier evening events alike.', 21),
      r('Isha', 5, 'This has replaced three other blazers in my closet — most versatile purchase this year.', 38, false),
    ],
  },
  {
    id: 'formal-shirt-men-01',
    name: 'Slim Fit Formal Shirt',
    brand: 'Arrow',
    category: 'Formal Wear',
    emoji: '👔',
    swatch: 'linear-gradient(135deg,#dfe6ee,#4a6fa5)',
    price: 1299,
    mrp: 1999,
    avgRating: 4.1,
    ratingCount: 1876,
    attributes: {
      fabric: 'Cotton-rich formal shirting fabric',
      fit: 'Slim fit, true to size for average build',
      occasion: 'Office, formal meetings, layered under blazers for events',
      reusability: 'Extremely high — weekly office wear',
      deliveryEstimate: '2-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Arjun', 5, 'Great everyday formal shirt, wear it weekly for office and it holds up well.', 4),
      r('Rohit', 4, 'True to size, slim fit looks sharp without being uncomfortable.', 18),
      r('Sanjay', 5, 'Bought five of these for the work week, consistent quality across all.', 30),
      r('Yash', 3, 'Fabric is decent but wrinkles a bit more than expected by evening.', 42),
      r('Vikram', 5, 'Perfect under a blazer for formal events too, very reusable piece.', 9),
      r('Karan', 4, 'Good quality cotton blend, true to size, comfortable for all-day wear.', 25),
      r('Aditya', 2, 'Buttons on one shirt came loose after just a few washes.', 56),
      r('Kabir', 5, 'Reuse these constantly for office, easily my most-worn item.', 13),
      r('Divya', 4, 'True to size, good stitching quality for the price point.', 37),
      r('Neha', 5, 'Bought for my husband, he wears these weekly and they hold up well.', 62),
      r('Priya', 3, 'Decent shirt but slim fit runs a touch tight around the arms.', 48),
      r('Isha', 4, 'Good everyday formal option, reusable and easy to maintain.', 21),
      r('Meera', 5, 'Great value, quality is consistent and true to size every time.', 6, false),
      r('Rahul', 4, 'Solid formal shirt, works well layered under a blazer for events.', 33),
      r('Tanvi', 5, 'Bought several for office, extremely reusable and good quality fabric.', 15),
    ],
  },
  {
    id: 'formal-trousers-men-03',
    name: 'Slim Fit Formal Trousers',
    brand: 'Van Heusen',
    category: 'Formal Wear',
    emoji: '👖',
    swatch: 'linear-gradient(135deg,#3a3a3a,#8a8a8a)',
    price: 1499,
    mrp: 2199,
    avgRating: 4.2,
    ratingCount: 1032,
    attributes: {
      fabric: 'Poly-viscose blend formal trouser fabric',
      fit: 'Slim fit, true to size through the waist, tapered leg',
      occasion: 'Office formals, interviews, paired with blazer for events',
      reusability: 'Extremely high — weekly office wear',
      deliveryEstimate: '3-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Rohit', 5, 'True to size through the waist, tapered leg looks sharp with formal shoes.', 5),
      r('Karan', 4, 'Good everyday office trouser, holds crease well through a long day.', 19),
      r('Sanjay', 5, 'Bought three pairs for the work week, consistent fit across all.', 32),
      r('Vikram', 3, 'Fabric is decent but slightly shiny under bright office lighting.', 44),
      r('Aditya', 5, 'Pairs perfectly with the matching blazer for interviews and formal events.', 8),
      r('Yash', 4, 'True to size, comfortable for all-day wear at the office.', 27, false),
      r('Kabir', 2, 'Waist ran slightly large even at my usual size, needed a belt.', 53),
      r('Arjun', 5, 'Extremely reusable, wear a pair of these to office almost daily.', 11),
      r('Rahul', 4, 'Good quality for the price, tapered fit looks modern and sharp.', 36),
      r('Priya', 5, 'Bought for my husband, he wears these constantly for work.', 3),
      r('Divya', 3, 'Decent trousers but fabric feels a bit thin for the price.', 49),
      r('Neha', 4, 'True to size, comfortable and holds shape well after washing.', 22),
      r('Simran', 5, 'Great everyday formal trouser, extremely reusable for office wear.', 16),
      r('Meera', 4, 'Good fit, pairs well with both the blazer and formal shirts.', 40),
      r('Isha', 3, 'Fine quality but the fabric wrinkles more than expected by evening.', 58),
    ],
  },
  {
    id: 'formal-blazer-women-04',
    name: 'Women’s Tailored Blazer',
    brand: 'AND',
    category: 'Formal Wear',
    emoji: '🧥',
    swatch: 'linear-gradient(135deg,#5a4a3a,#c9b896)',
    price: 2999,
    mrp: 4499,
    avgRating: 4.3,
    ratingCount: 578,
    attributes: {
      fabric: 'Structured poly-viscose blend with shoulder padding',
      fit: 'True to size, tailored fit through the waist',
      occasion: 'Office formals, client meetings, semi-formal evening events',
      reusability: 'Very high — office staple, reusable across seasons',
      deliveryEstimate: '3-5 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Ananya', 5, 'Perfect tailored fit for client meetings, true to size and looks sharp.', 6),
      r('Meera', 4, 'Great office staple, reused this constantly across different seasons.', 20),
      r('Riya', 3, 'Shoulder padding felt a bit stiff at first, softened after a few wears.', 34),
      r('Divya', 5, 'True to size, structured fit gives a very professional look for meetings.', 4),
      r('Isha', 4, 'Good quality blazer, reusable for both office and semi-formal evening events.', 42),
      r('Tanvi', 2, 'Fit was slightly loose at the waist even at my usual size.', 55),
      r('Neha', 5, 'Bought for client-facing meetings, feels polished and fits true to size.', 9),
      r('Simran', 4, 'Structured shoulders hold shape well, good tailored office piece.', 27),
      r('Priya', 5, 'This has become my go-to blazer for both work and dinners.', 13),
      r('Kabir', 3, 'Decent quality but fabric feels slightly synthetic up close.', 48),
      r('Pooja', 4, 'True to size, comfortable enough for a full day of meetings.', 31),
      r('Rahul', 5, 'Bought for my wife, she wears it constantly for office and events.', 3, false),
      r('Vikram', 4, 'Good structured fit, reusable investment piece for a working wardrobe.', 39),
      r('Aditya', 5, 'Perfect for interviews and client meetings, true to size and sharp looking.', 15),
      r('Sanjay', 3, 'Nice blazer but the lining felt a bit thin for the price.', 51),
    ],
  },
  {
    id: 'formal-shirt-women-05',
    name: 'Women’s Formal Shirt',
    brand: 'Van Heusen Woman',
    category: 'Formal Wear',
    emoji: '👔',
    swatch: 'linear-gradient(135deg,#e8e4f0,#c9a0d8)',
    price: 1099,
    mrp: 1699,
    avgRating: 4.1,
    ratingCount: 1289,
    attributes: {
      fabric: 'Cotton-rich formal shirting fabric',
      fit: 'True to size, relaxed office fit',
      occasion: 'Office wear, formal meetings, layered under a blazer',
      reusability: 'Extremely high — weekly office wear',
      deliveryEstimate: '2-4 days',
      returnPolicy: '15-day return',
    },
    reviews: [
      r('Priya', 5, 'Great everyday office shirt, wear it weekly and it holds up well.', 5),
      r('Ananya', 4, 'True to size, comfortable relaxed fit for long office days.', 17),
      r('Meera', 5, 'Bought five of these for the work week, consistent quality every time.', 29),
      r('Riya', 3, 'Fabric is decent but wrinkles a bit by the end of the day.', 41),
      r('Divya', 5, 'Perfect under my blazer for client meetings, very reusable piece.', 8),
      r('Isha', 4, 'Good quality cotton blend, true to size, comfortable all day.', 24),
      r('Tanvi', 2, 'A button came loose after just a couple of washes.', 54),
      r('Neha', 5, 'Reuse these constantly for office, easily my most-worn shirt.', 12),
      r('Simran', 4, 'True to size, good stitching quality for the price point.', 36),
      r('Pooja', 5, 'Bought several for work, they hold up well after many washes.', 3, false),
      r('Kabir', 3, 'Decent shirt but the relaxed fit runs a touch large for me.', 47),
      r('Vikram', 4, 'Good everyday formal option for my wife, reusable and easy to maintain.', 20),
      r('Rahul', 5, 'Great value, consistent quality and true to size every time.', 9),
      r('Sanjay', 4, 'Solid formal shirt, works well layered under a blazer for meetings.', 32),
      r('Aditya', 5, 'Bought several for office, extremely reusable and good fabric quality.', 14),
    ],
  },
];

export function getProductById(id: string): ShopProduct | undefined {
  return SHOP_PRODUCTS.find((p) => p.id === id);
}

export interface CategorySummary {
  category: string;
  emoji: string;
  swatch: string;
  count: number;
}

/** One tile per distinct category, using its first product's emoji/swatch as the tile art. */
export function getCategories(): CategorySummary[] {
  const seen = new Map<string, CategorySummary>();
  for (const p of SHOP_PRODUCTS) {
    const existing = seen.get(p.category);
    if (existing) {
      existing.count += 1;
    } else {
      seen.set(p.category, { category: p.category, emoji: p.emoji, swatch: p.swatch, count: 1 });
    }
  }
  return Array.from(seen.values());
}

/** Top-rated products for the homepage's "Trending Now" row. */
export function getTrendingProducts(limit = 6): ShopProduct[] {
  return [...SHOP_PRODUCTS].sort((a, b) => b.avgRating - a.avgRating).slice(0, limit);
}
